<?php

/**
 * Plugin Name: KWK Dev Media Proxy (mu-plugin)
 * Description: In local/dev only, rewrite media URLs to production so you don’t need a local uploads/ mirror.
 * Author: Tamar Marvin
 */

// Only run in development environment
if (function_exists('wp_get_environment_type') && wp_get_environment_type() !== 'development') {
    return; // bail on staging/prod
}

// ---- Set your production origin here ----
const KWK_PROD = 'https://kosherworldkitchen.com';

/**
 * Rewrite attachment URLs (featured images, attachment page, etc.).
 */
add_filter('wp_get_attachment_url', function ($url) {
    if (is_admin() || empty($url)) return $url;
    return preg_replace('#https?://[^/]+#', KWK_PROD, $url);
});

/**
 * Rewrite srcset candidates generated by WordPress so all variants come from prod.
 */
add_filter('wp_calculate_image_srcset', function ($sources) {
    if (is_admin() || !is_array($sources)) return $sources;
    foreach ($sources as &$s) {
        if (!empty($s['url'])) {
            $s['url'] = preg_replace('#https?://[^/]+#', KWK_PROD, $s['url']);
        }
    }
    return $sources;
}, 10, 1);

/**
 * Rewrite inline content images (blocks, WPRM content, etc.).
 */
add_filter('the_content', function ($html) {
    if (is_admin() || empty($html)) return $html;
    $local_prefix = trailingslashit(site_url('wp-content/uploads'));
    $prod_prefix  = trailingslashit(KWK_PROD . '/wp-content/uploads');
    return str_replace($local_prefix, $prod_prefix, $html);
}, 20);

/**
 * Safety: don’t rewrite admin screens, REST responses for uploads, or CLI.
 */
add_action('rest_api_init', function () {
    if (defined('WP_CLI') && WP_CLI) return;
});
